### ISSUE TITLE
Statboxes on right click should show stats for all objects where you clicked

### ISSUE THREAD

**Issue by JerryLin1** [p-han-tom/projectw#13]
Currently statboxes will only display stats (just the name currently but can be easily expanded) of the 
unit that you click on. 
![image](https://user-images.githubusercontent.com/21973246/75043750-8b74d380-548e-11ea-8e21-410a425fc1cf.png)
Other information like the descriptions of the tile, any items, and traps that occupy the same space should display below the unit's description.

**Todo**
- [x] Statbox stacking 😤 
- [x] Traps
- [ ] Tiles
- [ ] Actual stats once stats are added
- [ ] Have all statboxes have same width
- [ ] Make line separator between different statboxes

**Comment by JerryLin1** [comment]
possible completely obsoleted with scene2d??
